In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('./Youtube-Spam-Dataset.csv')
df.head()

COMMENT_ID            AUTHOR  \
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   

                  DATE                                            CONTENT  \
0  2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1  2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2  2013-11-08T17:34:21             just for test I have to say murdev.com   
3  2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^    
4  2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .   

                       VIDEO_NAME  CLASS  
0  PSY - GANGNAM STYLE(?????) M/V      1  
1  PSY - GANGNAM STYLE(?????) M/V      1  
2  PSY - GANGNAM STYLE(?????) M/V      1  
3  PSY - GANGNAM STYLE(?????) M/V      1  
4  PSY - GANGNAM STYLE(?????) M/V      1

In [3]:
X = df['CONTENT']
y = df['CLASS']

In [4]:
print(df['CONTENT'].isnull().sum())
df['CLASS'].isnull().sum()

0


0

In [5]:
from sklearn.model_selection import train_test_split 

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline

In [8]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('clf',LinearSVC())])

In [9]:
text_clf.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LinearSVC())])

In [10]:
predictions = text_clf.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [12]:
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test,predictions))

[[297  12]
 [ 20 317]]
              precision    recall  f1-score   support

           0       0.94      0.96      0.95       309
           1       0.96      0.94      0.95       337

    accuracy                           0.95       646
   macro avg       0.95      0.95      0.95       646
weighted avg       0.95      0.95      0.95       646

0.9504643962848297


In [13]:
def classify_spam(content:str):
    classify = text_clf.predict([content])
    if classify == [1]:
        content= content.upper()
        return f"{content} IS A SPAM MESSAGE"
    else:
        content= content.upper()
        return f"{content} is NOT a spam message" 

In [14]:
content =  'The boy is going home nigga'
classify_spam(content)

'THE BOY IS GOING HOME NIGGA is NOT a spam message'

'JOE'

In [16]:
from sklearn.linear_model import LogisticRegression 

In [17]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('clf',LogisticRegression())])

In [18]:
text_clf.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', LogisticRegression())])

In [19]:
predictions = text_clf.predict(X_test)

In [20]:
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test,predictions))

[[301   8]
 [ 22 315]]
              precision    recall  f1-score   support

           0       0.93      0.97      0.95       309
           1       0.98      0.93      0.95       337

    accuracy                           0.95       646
   macro avg       0.95      0.95      0.95       646
weighted avg       0.95      0.95      0.95       646

0.9535603715170279


In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('clf',RandomForestClassifier())])
text_clf.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf', RandomForestClassifier())])

In [23]:
predictions = text_clf.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test,predictions))

[[304   5]
 [ 30 307]]
              precision    recall  f1-score   support

           0       0.91      0.98      0.95       309
           1       0.98      0.91      0.95       337

    accuracy                           0.95       646
   macro avg       0.95      0.95      0.95       646
weighted avg       0.95      0.95      0.95       646

0.9458204334365325


In [24]:
from xgboost import XGBClassifier

In [25]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('clf',XGBClassifier())])
text_clf.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()),
                ('clf',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [26]:
predictions = text_clf.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test,predictions))

[[301   8]
 [ 25 312]]
              precision    recall  f1-score   support

           0       0.92      0.97      0.95       309
           1       0.97      0.93      0.95       337

    accuracy                           0.95       646
   macro avg       0.95      0.95      0.95       646
weighted avg       0.95      0.95      0.95       646

0.9489164086687306


In [54]:
from sklearn.svm import SVC

In [56]:
text_clf = Pipeline([('tfidf',TfidfVectorizer()),('clf',SVC())])
text_clf.fit(X_train,y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', SVC())])

In [58]:
predictions = text_clf.predict(X_test)
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
print(accuracy_score(y_test,predictions))

[[302   7]
 [ 23 314]]
              precision    recall  f1-score   support

           0       0.93      0.98      0.95       309
           1       0.98      0.93      0.95       337

    accuracy                           0.95       646
   macro avg       0.95      0.95      0.95       646
weighted avg       0.95      0.95      0.95       646

0.9535603715170279
